#!/bin/sh

set -e

NOW=$(date '+%Y%m%d')

GZIP=$(which gzip)
MYSQLDUMP=$(which mysqldump)

FILE=${BACKUP_FOLDER}/${MYSQL_DATABASE}-${NOW}.sql.gz
$MYSQLDUMP -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p${MYSQL_PASSWORD} --databases $MYSQL_DATABASE | $GZIP -9 > $FILE
