on:
  push:
    branches: [master]
    paths:
    - "*"
    - "!README.md"
    - "*.md"
    - "!docker-compose.yml"
    - "!LICENSE"

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: aquariumbio/database-backup
        tag_with_ref: true
        tag_with_sha: true
        add_git_labels: true